"""Coverage regressions using fixtures generated by this file at test runtime.

The independent scenario starts in July 2042 and lasts ten hours. Database rows,
timestamp spellings, invalid timestamp cases, and log events are constructed in
code. No captured database, log, message, or other external sample is loaded.
This describes the current generators, not the provenance of earlier fixtures.
"""
import contextlib
import datetime
import hashlib
import importlib.util
import io
import json
from pathlib import Path
import sqlite3
import tempfile
import unittest
from unittest import mock


SCRIPT = Path(__file__).resolve().parents[1] / 'scripts/lark-im-coverage-check.py'
SPEC = importlib.util.spec_from_file_location('coverage_check', SCRIPT)
check = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(check)
UTC = datetime.timezone.utc
EPOCH = datetime.datetime(1970, 1, 1, tzinfo=UTC)
DAY_MS = 24 * 60 * 60 * 1000
DEFAULT = object()


def build_timeline():
    origin = datetime.datetime(2042, 7, 19, 20, tzinfo=UTC)
    duration = datetime.timedelta(hours=10)
    start = int((origin - EPOCH).total_seconds() * 1000)
    span = int(duration.total_seconds() * 1000)
    return start, start + span // 2, start + span


START, MID, END = build_timeline()


def private_marker(field):
    return 'GENERATED_PRIVATE_VALUE_' + field.upper()


RECEIVED = check.RECEIVED_PREFIX + private_marker('scope')


def iso(ms):
    stamp = EPOCH + datetime.timedelta(milliseconds=ms)
    return stamp.isoformat(timespec='milliseconds')


def equivalent_timestamps(ms, timespec='seconds'):
    instant = EPOCH + datetime.timedelta(milliseconds=ms)
    for offset in (0, 180, -300):
        zone = datetime.timezone(datetime.timedelta(minutes=offset))
        value = instant.astimezone(zone).isoformat(timespec=timespec)
        yield value.replace('+00:00', 'Z') if offset == 0 else value


def invalid_timestamps(ms):
    instant = EPOCH + datetime.timedelta(milliseconds=ms)
    date = instant.date().isoformat()
    clock = instant.strftime('%H:%M:%S')
    minute = instant.strftime('%H:%M')
    bare = date + 'T' + clock
    week = instant.isocalendar()
    return (
        None, ms, True, '', date, bare, date + ' ' + clock + 'Z',
        instant.strftime('%Y%m%dT%H%M%SZ'),
        f'{week.year}-W{week.week:02d}-{week.weekday}T{clock}Z',
        bare + '+0300', bare + '+03', bare + '+03:00:30',
        date + 'T' + minute + '.1Z', bare + ',1Z', bare + '.0001Z',
        bare + 'z', bare + 'Z ', ' ' + bare + 'Z',
        f'{instant.year}-02-30T{clock}Z', date + 'T24:00:00Z',
        date + 'T' + minute + ':60Z', bare + '+24:00',
        bare + '+03:60', bare + '-03:60',
    )


def cursor(ms):
    return json.dumps({'kind': 'time_message_cursor/v1', 'created_at_ms': ms,
                       'source_time_precision': 'minute',
                       'meaning': 'scanned_until_inclusive'})


def file_state(path):
    stat = path.stat()
    return hashlib.sha256(path.read_bytes()).hexdigest(), stat.st_mtime_ns, stat.st_mode


def scope_values(key, enabled=1, current=END, reason=None, source='lark.im'):
    config = {} if reason is None else {'unsupported_reason': reason}
    return (key, source, enabled, json.dumps(config),
            None if current is None else cursor(current), iso(START))


def run_values(scope, left, right, status='succeeded', before=DEFAULT,
               after=DEFAULT, metadata=None, source='lark.im'):
    payload = {'window_start': iso(left), 'window_end': iso(right),
               'requested_window_end': iso(END), 'fetched_count': 0}
    if metadata:
        payload.update(metadata)
    if before is DEFAULT:
        before = None if left == START else cursor(left)
    if after is DEFAULT:
        after = cursor(right // check.MINUTE_MS * check.MINUTE_MS)
    return (source, scope, status, json.dumps(payload), before, after,
            iso(left), iso(right), private_marker('error'))


def seed_scenario(connection):
    """Create contract-shaped rows from the generated timeline, without samples."""
    connection.execute('INSERT INTO sources VALUES(?,?,?)',
                       ('lark.im', 1, json.dumps({'initial_sync_start_ms': START})))
    rows = [scope_values(key) for key in (check.SENT_ID, RECEIVED)]
    discovery = {'kind': 'chat_discovery_cursor/v1', 'has_more': False,
                 'completed_at': iso(END), 'pages_scanned': 1}
    rows.append((check.DISCOVERY_ID, 'lark.im', 1, '{}', json.dumps(discovery), iso(START)))
    connection.executemany('INSERT INTO sync_scopes VALUES(?,?,?,?,?,?)', rows)
    connection.execute('''INSERT INTO sync_runs(source_id,scope_id,status,metadata_json,
        cursor_before_json,cursor_after_json,started_at,finished_at,error_type)
        VALUES(?,?,?,?,?,?,?,?,?)''', run_values(check.SENT_ID, START, END))


def log_events():
    return [
        {'type': private_marker('other_event'), 'body': private_marker('body')},
        {'type': 'lark_im_worker_cycle', 'cycle': 4,
         'at': iso(START + (END - START) // 4), 'ok': False,
         'failed_steps': ['sent', private_marker('step')],
         'message': private_marker('log_message')},
    ]


class CoverageTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory(prefix='coverage-check-synthetic-')
        self.addCleanup(self.tmp.cleanup)
        self.path = Path(self.tmp.name) / 'synthetic.sqlite'
        self.con = sqlite3.connect(self.path)
        self.addCleanup(self.con.close)
        self.con.executescript('''
            CREATE TABLE sources(id TEXT PRIMARY KEY,enabled INTEGER,config_json TEXT);
            CREATE TABLE sync_scopes(id TEXT PRIMARY KEY,source_id TEXT,enabled INTEGER,
                config_json TEXT,cursor_json TEXT,created_at TEXT);
            CREATE TABLE sync_runs(id INTEGER PRIMARY KEY,source_id TEXT,scope_id TEXT,status TEXT,
                metadata_json TEXT,cursor_before_json TEXT,cursor_after_json TEXT,
                started_at TEXT,finished_at TEXT,error_type TEXT,scanned_count INTEGER DEFAULT 0);
            CREATE TABLE records(id INTEGER PRIMARY KEY,body TEXT);
            CREATE TABLE sync_locks(scope_id TEXT);
        ''')
        seed_scenario(self.con)

    def scope(self, key, enabled=1, current=END, reason=None, source='lark.im'):
        self.con.execute('INSERT INTO sync_scopes VALUES(?,?,?,?,?,?)',
                         scope_values(key, enabled, current, reason, source))

    def run_window(self, scope, left, right, status='succeeded', before=DEFAULT,
                   after=DEFAULT, metadata=None, source='lark.im'):
        self.con.execute('''INSERT INTO sync_runs(source_id,scope_id,status,metadata_json,
            cursor_before_json,cursor_after_json,started_at,finished_at,error_type)
            VALUES(?,?,?,?,?,?,?,?,?)''',
                         run_values(scope, left, right, status, before, after, metadata, source))

    def set_baseline(self, value):
        self.con.execute('UPDATE sources SET config_json=? WHERE id=?',
                         (json.dumps({'initial_sync_start_ms': value}), 'lark.im'))

    def inspect(self, target=END):
        self.con.commit()
        return check.inspect_database(self.path, target)

    def assert_complete(self, out, expected):
        self.assertEqual(out['coverage']['initial_baseline_complete'], expected)
        self.assertEqual(out['progress']['initial_baseline_at_target'], int(expected))

    def cli(self, *extra, target=END):
        output = io.StringIO()
        self.con.commit()
        with contextlib.redirect_stdout(output):
            result = check.main(['--db', str(self.path), '--target', iso(target), *extra])
        return result, json.loads(output.getvalue())

    def test_contiguous_zero_record_successful_windows(self):
        self.run_window(RECEIVED, START, MID)
        self.run_window(RECEIVED, MID, END)
        out = self.inspect()
        self.assert_complete(out, True)
        self.assertEqual(out['coverage']['eligible_successful_runs'], 3)
        self.assertEqual(out['coverage']['missing_scope_milliseconds'], 0)

    def test_late_start_after_midnight_is_not_complete(self):
        late = (START // DAY_MS + 1) * DAY_MS
        self.run_window(RECEIVED, late, END, before=None)
        out = self.inspect()
        self.assertEqual(out['progress']['cursor_endpoints_at_target'], 1)
        self.assert_complete(out, False)
        self.assertEqual(out['coverage']['scopes_missing_start_coverage'], 1)

    def test_gap_cannot_be_filled_by_failed_cancelled_or_running_rows(self):
        self.run_window(RECEIVED, START, MID)
        self.run_window(RECEIVED, MID + 60_000, END)
        for status in ('failed', 'cancelled', 'running'):
            self.run_window(RECEIVED, START, END, status=status)
        out = self.inspect()
        self.assert_complete(out, False)
        self.assertEqual(out['coverage']['scopes_with_internal_gaps'], 1)
        self.assertEqual(out['coverage']['missing_scope_milliseconds'], 60_000)
        self.assertEqual(out['coverage']['non_succeeded_runs_ignored'], 3)

    def test_overlap_replay_duplicate_and_unordered_rows_are_valid(self):
        self.run_window(RECEIVED, MID, END)
        self.run_window(RECEIVED, START, MID + 30_000)
        self.run_window(RECEIVED, START, MID + 30_000)
        out = self.inspect()
        self.assert_complete(out, True)
        self.assertEqual(out['coverage']['covered_scope_milliseconds'], 2 * (END - START))

    def test_target_cursor_without_run_evidence_is_insufficient(self):
        out = self.inspect()
        self.assert_complete(out, False)
        self.assertEqual(out['coverage']['scopes_without_eligible_successful_runs'], 1)
        self.assertEqual(out['progress']['cursor_endpoints_at_target'], 1)

    def test_missing_current_cursor_cannot_pass_with_complete_runs(self):
        self.run_window(RECEIVED, START, END)
        self.con.execute('UPDATE sync_scopes SET cursor_json=NULL WHERE id=?', (RECEIVED,))
        out = self.inspect()
        self.assert_complete(out, False)
        self.assertTrue(out['coverage']['successful_windows_cover_fixed_range'])
        self.assertEqual(out['progress']['missing_or_invalid_cursor'], 1)

    def test_current_cursor_one_ms_behind_target_fails(self):
        self.run_window(RECEIVED, START, END)
        self.con.execute('UPDATE sync_scopes SET cursor_json=? WHERE id=?',
                         (cursor(END - 1), RECEIVED))
        self.assert_complete(self.inspect(), False)

    def test_current_cursor_above_target_still_requires_complete_evidence(self):
        self.con.execute('UPDATE sync_scopes SET cursor_json=? WHERE id=?',
                         (cursor(END + DAY_MS), RECEIVED))
        self.assert_complete(self.inspect(), False)
        self.run_window(RECEIVED, START, END)
        self.assert_complete(self.inspect(), True)

    def test_disabled_unsupported_scopes_are_reported_separately(self):
        self.run_window(RECEIVED, START, END)
        self.scope(RECEIVED + '-disabled', enabled=0, current=None, reason='restricted_mode')
        self.scope(RECEIVED + '-out', enabled=0, current=None, reason='bot_user_out_of_chat')
        self.scope(RECEIVED + '-ordinary', enabled=0, current=None)
        out = self.inspect()
        self.assert_complete(out, True)
        self.assertEqual(out['coverage']['enabled_message_scopes'], 2)
        self.assertEqual(out['coverage']['disabled_excluded']['unsupported'], 2)
        self.assertEqual(out['coverage']['disabled_excluded']['other'], 1)

    def test_enabled_unsupported_scope_is_visible_and_not_silently_ignored(self):
        self.run_window(RECEIVED, START, END)
        self.scope(RECEIVED + '-unsupported', reason=private_marker('unsupported'))
        out = self.inspect()
        self.assert_complete(out, False)
        self.assertEqual(out['coverage']['enabled_unsupported_scopes'], 1)
        self.assertEqual(out['coverage']['enabled_message_scopes'], 3)
        self.assertNotIn(private_marker('unsupported'), json.dumps(out))

    def test_disabled_sent_never_counts_as_success(self):
        self.run_window(RECEIVED, START, END)
        self.con.execute('UPDATE sync_scopes SET enabled=0 WHERE id=?', (check.SENT_ID,))
        self.assert_complete(self.inspect(), False)

    def test_missing_baseline_is_not_inferred_from_scopes_or_runs(self):
        self.run_window(RECEIVED, START, END)
        self.con.execute("UPDATE sources SET config_json='{}'")
        out = self.inspect()
        self.assert_complete(out, False)
        self.assertEqual(out['coverage']['baseline_status'], 'initial_sync_start_missing')
        self.assertIsNone(out['coverage']['required_start_ms'])

    def test_invalid_baseline_types_and_values_fail_closed(self):
        self.run_window(RECEIVED, START, END)
        for value in (str(START), True, False, None, [], {}, START + 0.5, -1):
            with self.subTest(value=value):
                self.set_baseline(value)
                out = self.inspect()
                self.assert_complete(out, False)
                self.assertEqual(out['coverage']['baseline_status'], 'initial_sync_start_invalid')
                self.assertIsNone(out['coverage']['required_start_ms'])

    def test_seconds_baseline_and_out_of_range_milliseconds_are_rejected(self):
        for value in (START // 1000, 99_999_999_999, 253_402_300_800_000):
            with self.subTest(value=value):
                self.set_baseline(value)
                out = self.inspect()
                self.assert_complete(out, False)
                self.assertEqual(out['coverage']['baseline_status'], 'initial_sync_start_invalid')

    def test_baseline_range_bounds_are_accepted_as_baselines(self):
        for value in (100_000_000_000, 253_402_300_799_999):
            with self.subTest(value=value):
                self.set_baseline(value)
                out = self.inspect()
                self.assertEqual(out['coverage']['baseline_status'], 'ok')
                self.assertEqual(out['coverage']['required_start_ms'], value)

    def test_nonfinite_or_malformed_source_config_is_rejected(self):
        for config in ('{', 'null', '[]', '{"initial_sync_start_ms":NaN}',
                       '{"initial_sync_start_ms":Infinity}',
                       '{"initial_sync_start_ms":1e999}'):
            with self.subTest(config=config):
                self.con.execute('UPDATE sources SET config_json=?', (config,))
                out = self.inspect()
                self.assert_complete(out, False)
                self.assertNotEqual(out['coverage']['baseline_status'], 'ok')

    def test_missing_or_disabled_source_fails(self):
        self.run_window(RECEIVED, START, END)
        self.con.execute('UPDATE sources SET enabled=0')
        out = self.inspect()
        self.assert_complete(out, False)
        self.assertEqual(out['coverage']['baseline_status'], 'source_disabled')
        self.con.execute('DELETE FROM sources')
        out = self.inspect()
        self.assert_complete(out, False)
        self.assertEqual(out['coverage']['baseline_status'], 'source_missing')

    def test_target_equal_to_or_before_baseline_is_not_complete(self):
        self.run_window(RECEIVED, START, END)
        for target in (START, START - 1):
            with self.subTest(target=target):
                out = self.inspect(target)
                self.assert_complete(out, False)
                self.assertEqual(out['coverage']['range_status'], 'target_not_after_baseline')
                self.assertIsNone(out['coverage']['missing_scope_milliseconds'])
                result, cli_out = self.cli(target=target)
                self.assertEqual(result, 2)
                self.assertFalse(cli_out['coverage']['initial_baseline_complete'])

    def test_bisection_only_credits_completed_prefix(self):
        self.run_window(RECEIVED, START, MID, metadata={'window_bisections': 3})
        partial = self.inspect()
        self.assert_complete(partial, False)
        self.assertEqual(partial['coverage']['scopes_missing_end_coverage'], 1)
        self.run_window(RECEIVED, MID, END)
        self.assert_complete(self.inspect(), True)

    def test_requested_end_cannot_replace_actual_completed_end(self):
        self.run_window(RECEIVED, START, MID,
                        metadata={'requested_window_end': iso(END + DAY_MS)})
        out = self.inspect()
        self.assert_complete(out, False)
        self.assertEqual(out['coverage']['missing_scope_milliseconds'], END - MID)

    def test_invalid_before_after_or_metadata_cannot_supply_evidence(self):
        cases = [({'before': cursor(START + 60_000)}, 'invalid_cursor_before'),
                 ({'before': '{}'}, 'invalid_cursor_before'),
                 ({'after': None}, 'invalid_cursor_after'),
                 ({'after': cursor(END + 60_000)}, 'invalid_cursor_after'),
                 ({'after': cursor(MID)}, 'invalid_cursor_after'),
                 ({'metadata': {'window_start': iso(START).removesuffix('+00:00')}}, 'invalid_window'),
                 ({'metadata': {'window_end': None}}, 'invalid_window')]
        for options, expected in cases:
            with self.subTest(expected=expected, options=options):
                self.con.execute('DELETE FROM sync_runs WHERE scope_id=?', (RECEIVED,))
                self.run_window(RECEIVED, START, END, **options)
                out = self.inspect()
                self.assert_complete(out, False)
                self.assertEqual(out['coverage']['invalid_successful_run_reasons'], {expected: 1})

    def test_zero_length_and_reversed_run_windows_never_fill_coverage(self):
        for left, right in ((START, START), (MID, START)):
            with self.subTest(left=left, right=right):
                self.con.execute('DELETE FROM sync_runs WHERE scope_id=?', (RECEIVED,))
                self.run_window(RECEIVED, left, right)
                out = self.inspect()
                self.assert_complete(out, False)
                self.assertEqual(out['coverage']['missing_scope_milliseconds'], END - START)

    def test_skipped_successful_run_is_not_coverage(self):
        self.run_window(RECEIVED, START, END, metadata={'skipped': True})
        out = self.inspect()
        self.assert_complete(out, False)
        self.assertEqual(out['coverage']['skipped_successful_runs'], 1)

    def test_other_scope_or_source_cannot_fill_hole(self):
        self.run_window(RECEIVED, MID, END)
        self.scope(RECEIVED + '-other')
        self.run_window(RECEIVED + '-other', START, END)
        self.run_window(RECEIVED, START, END, source='other-source')
        out = self.inspect()
        self.assert_complete(out, False)
        self.assertEqual(out['coverage']['scopes_missing_start_coverage'], 1)

    def test_cross_day_target_uses_full_requested_range(self):
        target = END + 2 * DAY_MS
        self.run_window(RECEIVED, START, END)
        for scope in (check.SENT_ID, RECEIVED):
            self.con.execute('UPDATE sync_scopes SET cursor_json=? WHERE id=?',
                             (cursor(target), scope))
        self.assert_complete(self.inspect(target), False)
        for scope in (check.SENT_ID, RECEIVED):
            self.run_window(scope, END, target)
        out = self.inspect(target)
        self.assert_complete(out, True)
        self.assertEqual(out['coverage']['target_ms'], target)
        self.assertEqual(out['progress']['target_ms'], target)
        self.assertEqual(out['coverage']['covered_scope_milliseconds'], 2 * (target - START))

    def test_different_databases_have_independent_dynamic_baselines(self):
        self.run_window(RECEIVED, START, END)
        self.con.commit()
        other_path = self.path.parent / 'other-synthetic.sqlite'
        other = sqlite3.connect(other_path)
        self.addCleanup(other.close)
        self.con.backup(other)
        later = START + 3 * 60 * 60 * 1000
        other.execute('UPDATE sources SET config_json=?',
                      (json.dumps({'initial_sync_start_ms': later}),))
        other.commit()
        original = check.inspect_database(self.path, END)
        shifted = check.inspect_database(other_path, END)
        self.assert_complete(original, True)
        self.assert_complete(shifted, True)
        self.assertEqual(original['coverage']['required_start_ms'], START)
        self.assertEqual(shifted['coverage']['required_start_ms'], later)
        self.assertEqual(shifted['coverage']['covered_scope_milliseconds'], 2 * (END - later))

    def test_earlier_baseline_exposes_missing_history(self):
        self.run_window(RECEIVED, START, END)
        earlier = START - DAY_MS
        self.set_baseline(earlier)
        out = self.inspect()
        self.assert_complete(out, False)
        self.assertEqual(out['coverage']['baseline_status'], 'ok')
        self.assertEqual(out['coverage']['required_start_ms'], earlier)
        self.assertEqual(out['coverage']['scopes_missing_start_coverage'], 2)
        self.assertEqual(out['coverage']['missing_scope_milliseconds'], 2 * DAY_MS)

    def test_no_fixed_constants_or_observation_cohort_remain(self):
        self.assertFalse(hasattr(check, 'START_MS'))
        self.assertFalse(hasattr(check, 'TARGET_MS'))
        self.assertNotIn('initial_observation_cohort', self.inspect())

    def test_output_is_aggregate_and_database_is_unchanged(self):
        self.run_window(RECEIVED, START, END,
                        metadata={'private': private_marker('metadata')})
        self.run_window(RECEIVED, START, END, status='failed')
        self.con.execute('INSERT INTO records(body) VALUES(?)', (private_marker('body'),))
        self.con.commit()
        before = file_state(self.path), self.path.parent.stat().st_mode
        rendered = json.dumps(check.inspect_database(self.path, END))
        after = file_state(self.path), self.path.parent.stat().st_mode
        self.assertEqual(before, after)
        for sentinel in (*[private_marker(field) for field in ('scope', 'metadata', 'body', 'error')],
                         check.SENT_ID, str(self.path)):
            self.assertNotIn(sentinel, rendered)

    def test_wal_commits_are_visible_without_changing_db_wal_or_business_state(self):
        self.con.commit()
        self.assertEqual(self.con.execute('PRAGMA journal_mode=WAL').fetchone()[0], 'wal')
        self.con.execute('PRAGMA wal_autocheckpoint=0')
        # This successful received window exists only in WAL at inspection time.
        self.run_window(RECEIVED, START, END)
        self.con.commit()
        files = [self.path, Path(str(self.path) + '-wal')]
        shm = Path(str(self.path) + '-shm')
        for path in [*files, shm]:
            self.assertTrue(path.exists())
        tables = ('sources', 'sync_scopes', 'sync_runs', 'records', 'sync_locks')
        business_before = {table: self.con.execute('SELECT * FROM ' + table).fetchall()
                           for table in tables}
        before = {path.name: file_state(path) for path in files}
        names_before = {path.name for path in self.path.parent.iterdir()}
        parent_mode = self.path.parent.stat().st_mode
        shm_mode = shm.stat().st_mode
        out = check.inspect_database(self.path, END)
        self.assert_complete(out, True)
        after = {path.name: file_state(path) for path in files}
        business_after = {table: self.con.execute('SELECT * FROM ' + table).fetchall()
                          for table in tables}
        self.assertEqual(before, after, 'read-only inspection modified DB or WAL')
        self.assertEqual(business_before, business_after)
        self.assertEqual(names_before, {path.name for path in self.path.parent.iterdir()})
        self.assertEqual(parent_mode, self.path.parent.stat().st_mode)
        # SQLite may update SHM reader coordination; permissions must stay intact.
        self.assertEqual(shm_mode, shm.stat().st_mode)

    def test_cli_exit_codes_and_missing_database_fail_closed(self):
        self.assertEqual(self.cli()[0], 2)
        self.run_window(RECEIVED, START, END)
        self.assertEqual(self.cli()[0], 0)
        missing = self.path.parent / (private_marker('missing_database') + '.sqlite')
        output = io.StringIO()
        with contextlib.redirect_stdout(output):
            result = check.main(['--db', str(missing), '--target', iso(END)])
        self.assertEqual(result, 2)
        self.assertFalse(missing.exists())
        self.assertNotIn(str(missing), output.getvalue())
        self.assertNotIn(missing.name, output.getvalue())

    def test_missing_database_direct_inspection_does_not_create_file(self):
        missing = self.path.parent / 'direct-missing.sqlite'
        with self.assertRaises((sqlite3.Error, OSError, ValueError)):
            check.inspect_database(missing, END)
        self.assertFalse(missing.exists())

    def test_cli_requires_target_before_attempting_database_access(self):
        with mock.patch.object(check, 'inspect_database') as inspect:
            with contextlib.redirect_stderr(io.StringIO()), self.assertRaises(SystemExit) as raised:
                check.main(['--db', str(self.path)])
            self.assertEqual(raised.exception.code, 2)
            inspect.assert_not_called()

    def test_cli_millisecond_targets_and_timezone_offsets_are_equivalent(self):
        next_minute = END + check.MINUTE_MS
        self.run_window(check.SENT_ID, END, next_minute)
        self.run_window(RECEIVED, START, next_minute)
        self.con.execute('UPDATE sync_scopes SET cursor_json=? WHERE id IN (?,?)',
                         (cursor(next_minute), check.SENT_ID, RECEIVED))
        self.con.commit()
        target_ms = END + 271
        for target in equivalent_timestamps(target_ms, timespec='milliseconds'):
            with self.subTest(target=target):
                output = io.StringIO()
                with contextlib.redirect_stdout(output):
                    result = check.main(['--db', str(self.path), '--target', target])
                self.assertEqual(result, 0)
                out = json.loads(output.getvalue())
                self.assertEqual(out['coverage']['target_ms'], target_ms)
                self.assertEqual(out['progress']['target_ms'], target_ms)
                self.assertEqual(out['coverage']['target_utc'], iso(target_ms).replace('+00:00', 'Z'))

    def test_cli_foreign_key_failure_blocks_success_despite_complete_coverage(self):
        self.run_window(RECEIVED, START, END)
        foreign_table = private_marker('foreign_table')
        self.con.executescript(f'''
            CREATE TABLE private_parent(id INTEGER PRIMARY KEY);
            CREATE TABLE {foreign_table}(
                parent_id INTEGER REFERENCES private_parent(id));
            INSERT INTO {foreign_table} VALUES(7);
        ''')
        result, out = self.cli()
        self.assert_complete(out, True)
        self.assertEqual(out['foreign_key_issues'], [{'count': 1}])
        self.assertFalse(out['database_checks_ok'])
        self.assertFalse(out['ok'])
        self.assertEqual(result, 2)
        self.assertNotIn(foreign_table, json.dumps(out))

    def test_cli_rejects_invalid_target_before_database_access(self):
        values = [value for value in invalid_timestamps(END) if isinstance(value, str)]
        for target in (*values, str(END), 'not-a-time'):
            with self.subTest(target=target), mock.patch.object(check, 'inspect_database') as inspect:
                with contextlib.redirect_stderr(io.StringIO()), self.assertRaises(SystemExit) as raised:
                    check.main(['--db', str(self.path), '--target', target])
                self.assertEqual(raised.exception.code, 2)
                inspect.assert_not_called()

    def test_cli_rejects_skip_log_and_report_output_options(self):
        for extra in (['--skip-log'], ['report.json'], ['--output', 'report.json']):
            with self.subTest(extra=extra), mock.patch.object(check, 'inspect_database') as inspect:
                with contextlib.redirect_stderr(io.StringIO()), self.assertRaises(SystemExit) as raised:
                    check.main(['--db', str(self.path), '--target', iso(END), *extra])
                self.assertEqual(raised.exception.code, 2)
                inspect.assert_not_called()

    def test_default_db_is_project_relative_and_log_is_opt_in(self):
        output = io.StringIO()
        result = {'ok': True, 'coverage': {'initial_baseline_complete': True}}
        with mock.patch.object(check, 'inspect_database', return_value=result) as inspect:
            with mock.patch.object(check, 'recent_cycles') as cycles:
                with contextlib.redirect_stdout(output):
                    self.assertEqual(check.main(['--target', iso(END)]), 0)
                inspect.assert_called_once()
                args, kwargs = inspect.call_args
                self.assertEqual(Path(args[0]), SCRIPT.parent.parent / 'data/exocortex.sqlite')
                self.assertEqual(args[1] if len(args) > 1 else kwargs['target_ms'], END)
                cycles.assert_not_called()
        self.assertTrue(json.loads(output.getvalue())['coverage']['initial_baseline_complete'])

    def test_explicit_synthetic_log_is_aggregate_and_unchanged(self):
        self.run_window(RECEIVED, START, END)
        log = self.path.parent / (private_marker('log_path') + '.jsonl')
        log.write_text('\n'.join(json.dumps(event) for event in log_events()) + '\n', encoding='utf-8')
        before = file_state(log)
        result, out = self.cli('--log', str(log))
        self.assertEqual(result, 0)
        self.assertEqual(file_state(log), before)
        self.assertEqual(out['recent_cycles'][0]['failed_steps'], ['sent', 'other'])
        rendered = json.dumps(out)
        for sentinel in (private_marker(field) for field in ('body', 'step', 'log_message', 'log_path')):
            self.assertNotIn(sentinel, rendered)


class TimestampAndIntervalTests(unittest.TestCase):
    def test_strict_iso_accepts_utc_offsets_and_optional_seconds(self):
        for text in (*equivalent_timestamps(END), *equivalent_timestamps(END, timespec='minutes')):
            with self.subTest(text=text):
                self.assertEqual(check.iso_ms(text), END)
        for text in equivalent_timestamps(START):
            self.assertEqual(check.iso_ms(text), START)

    def test_strict_iso_retains_exact_milliseconds(self):
        whole_seconds = next(equivalent_timestamps(END)).removesuffix('Z')
        for fraction in ('7', '43', '681'):
            with self.subTest(fraction=fraction):
                delta = int(fraction.ljust(3, '0'))
                self.assertEqual(check.iso_ms(whole_seconds + '.' + fraction + 'Z'), END + delta)

    def test_strict_iso_rejects_nonstandard_or_imprecise_timestamps(self):
        for value in invalid_timestamps(END):
            with self.subTest(value=value):
                self.assertIsNone(check.iso_ms(value))

    def test_interval_union_clips_replays_and_ignores_order(self):
        result = check.interval_coverage(
            [(MID, END + DAY_MS), (START - DAY_MS, MID), (START, MID)], START, END)
        self.assertTrue(result['complete'])
        self.assertEqual(result['covered_ms'], END - START)
        self.assertEqual(result['missing_ms'], 0)

    def test_interval_one_millisecond_gap_is_not_complete(self):
        result = check.interval_coverage([(START, MID), (MID + 1, END)], START, END)
        self.assertFalse(result['complete'])
        self.assertEqual(result['missing_ms'], 1)
        self.assertEqual(result['internal_gaps'], 1)

    def test_interval_empty_or_reversed_range_is_not_complete(self):
        for target in (START, START - 1):
            with self.subTest(target=target):
                with self.assertRaises(ValueError):
                    check.interval_coverage([(START - DAY_MS, END)], START, target)


if __name__ == '__main__':
    unittest.main()
